/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type { CommonABI, CommonABIInterface } from "../CommonABI";

const _abi = ["function claimReward() external"];

export class CommonABI__factory {
  static readonly abi = _abi;
  static createInterface(): CommonABIInterface {
    return new utils.Interface(_abi) as CommonABIInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): CommonABI {
    return new Contract(address, _abi, signerOrProvider) as CommonABI;
  }
}
